version: '3.9'
services:
  gptchatbot:
    image: gpt-chat:latest
    container_name: gptchatbot
    build: .
    restart: always

    # Specify a .env file for credentials
    # the `AWS_INSTANCE_URL` environment variable will be prepended to that file
    env_file: .env

    volumes:
      - .:/app
